
project_id = "egwvjgvymxwjtkkvjune"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://ab35a25c-20b3-4577-a064-dba1aab459cf.lovableproject.com"
additional_redirect_urls = ["https://egwvjgvymxwjtkkvjune.supabase.co", "https://ab35a25c-20b3-4577-a064-dba1aab459cf.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.like_video]
verify_jwt = true
