// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egwvjgvymxwjtkkvjune.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnd3ZqZ3Z5bXh3anRra3ZqdW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTUwNjQsImV4cCI6MjA2NDk3MTA2NH0.GiQA_eucLJtGq7cFpi4EfKx_a8eurLMj0Eu7h9f5qvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);